### PR TITLE
Continuous deployments

### PR DESCRIPTION
**Pull request by rogeruiz**
This patch series adds CircleCI configuration and updated documentation around manual and automated deployments.

### CODE REVIEW

**Comment by rogeruiz** [comment]
We're on CircleCI now 🎉 

screen shot 2016-05-23 at 4 59 26 pm

I think this can land on `staging` and we can clean up these linting errors and warnings in a separate PR.

cc @theresaanna @maya

**Comment by rogeruiz** [comment]
I added a separate Issue to track the linting errors and warnings for the current codebase here => #51

**Comment by rogeruiz** [comment]
The #52 branch needs to be merged into this branch before we can merge this PR.

Could you take a look at this @theresaanna? Thanks!

**Comment by theresaanna** [comment]
Hooray for linting, testing setup and CI!

**Comment by yozlet** [comment]
Looking at this now from THE FUTURE - @rogeruiz, why do we delete `node_modules`? Don't we want Circle to cache it for us?

**Comment by rogeruiz** [comment]
@yozlet, what I was running into was a problem with the `libsass` bindings becoming irrelevant / corrupted when the cached npm modules directory was reused. We need that library for `node-sass` which compiles the C library on `npm postinstall` of `node-sass` and sets up the bindings for Node.

**Pull request merged**
