### PR TITLE
[ work in progress ] Update docs with URLs and clarification

### PR DESCRIPTION
**Pull request by rogeruiz**
This patch updates the `README` with staging and production URLs at the top for better visibility :eyes: and updates the description to match the Github description at the top of the page.

cc: @kategarklavs

### CODE REVIEW

**Comment by rogeruiz** [comment]
I can fix the conflicts on this branch, looks like it's just the `readme` changes from #70

**Comment by rogeruiz** [comment]
This branch is rebased, reviewed by @kategarklavs, and ready to be merged in 🎉  @maya @yozlet @theresaanna

**Comment by rogeruiz** [comment]
Once #78 lands, I want to update the documentation to show the multilingual deployment process to close #62

**Comment by jpyuda** [comment]
This one is OBE

**Pull request closed without merging**
