### PR TITLE
Update installation / development documentation

### PR DESCRIPTION
**Pull request by rogeruiz**
These installation instructions will quickly get a user up and running with the project. I would like to flesh them out a little with your help @kategarklavs. Thanks!

### CODE REVIEW

**Comment by maya** [comment]
Do we want it to match what we have for the microsite? It would be nice if all FFD Hugo projects had the same installation instructions. https://github.com/18F/ffd-microsite

**Comment by rogeruiz** [comment]
@maya good call. I will update this tomorrow.

**Comment by maya** [comment]
@rogeruiz any updates on this? Should we merge it in and make a note to bring them in line at a later point?

**Comment by rogeruiz** [comment]
@maya I'll have an update for this today. I realized that we didn't have this in the `ffd-toolkit` repo. so this PR and the PR for the toolkit will both be done today.

**Comment by rogeruiz** [comment]
I brought in all the work we did in the `ffd-microsite` related to the Readme documentation. I know that @kategarklavs has seen it in that repo, but I will cross-ref the `ffd-toolkit` PR into this one as well so we can keep them in sync.

Feel free to review this one before we pull in the final one into `ffd-toolkit`.

**Comment by maya** [comment]
Looks good! 👌

**Pull request merged**
