### PR TITLE
changing "reside" to "live"

### PR DESCRIPTION
**Pull request by jpyuda**
Following guidance from the plain language act.

### CODE REVIEW

**Comment by jpyuda** [comment]
@kategarklavs can you write a sentence or two clarifying what we mean by "live" as per discussion in the previous pull request? I can get it integrated into the site, then.

**Comment by jamesharnett** [comment]
> To have one's permanent home in a particular place.

**Comment by kategarklavs** [comment]
@jamesharnett Howdy, and thanks for providing this. How would you all feel about the following?

"To live somewhere is to make that place your permanent home. When answering the following questions, refer to your permanent home."

(If that second sentence is overkill, I'm OK dropping it.)

**Comment by megdaly** [comment]
@kategarklavs That sounds good!

**Comment by megdaly** [comment]
For states that have don't have online registration and offers the registration form, change "requires" to "allows", since people can still register in person. 
Ex: Florida requires residents to register by mail.

**Comment by kategarklavs** [comment]
@megdaly Hey! Thanks for your feedback (and the "requires/allows" change sound good to me).

**Comment by kategarklavs** [comment]
@megdaly Also, let me know if you'd like me to merge 👍

**Comment by megdaly** [comment]
@kategarklavs Sure, feel free to merge. Thanks!

**Comment by jamesharnett** [comment]
One thing to note with "allows", you may want to make sure they know there is no online registration, as it may be seen as ambiguous. I recommend changing the format to:

> New Jersey allows residents to register by mail, not online.

**Comment by kategarklavs** [comment]
@jamesharnett That's a good point (re: ambiguity) — I'm in favor of clarifying _allows_.

**Comment by megdaly** [comment]
Great suggestion James. I like your suggestion to clarify allows. Many, if not all, states also allow in person registration at various locations, so would be worth mentioning that as well.

**Pull request merged**
