### PR TITLE
Update Rhode Island to online registration

### PR DESCRIPTION
**Pull request by jpyuda**
What it says on the tin

### CODE REVIEW

**Comment by jamesharnett** [comment]
The online link for Rhode Island's voter registration is incorrect. It is `https://vote.sos.ri.gov`, not `https://vote.ri.gov`.

**Comment by jpyuda** [comment]
vote.ri.gov redirects to their english-language form (and vota.ri.gov to the spanish-language). Given that those are the URLs I've seen them promoting, they seem the safe ones to use.

**Comment by rogeruiz** [comment]
Looks good. Are we worried about this prompt @jpyuda? If not, I'll quickly merge this in.

screen shot 2016-08-08 at 9 47 14 am

**Comment by jpyuda** [comment]
updating the link since the SSL cert on their redirect isn't working anymore.

**Pull request merged**
